"""
Runtime-generated script: reads gantt_chart.md and produces
gantt_chart.xlsx (5 sheets) and gantt_tasks.csv.
Generated by gantt-chart-creator skill on 2026-05-07.
Updated 2026-06-10: added --gantt/--excel/--csv CLI args for custom project folders.
"""

import argparse
import re
import csv
import sys
from pathlib import Path
from datetime import date, timedelta
import openpyxl
from openpyxl.styles import (
    PatternFill, Font, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter

# ---------------------------------------------------------------------------
# Paths — resolved from CLI args or defaults
# ---------------------------------------------------------------------------

def _resolve_paths():
    parser = argparse.ArgumentParser(
        description="Generate gantt_chart.xlsx and gantt_tasks.csv from gantt_chart.md"
    )
    root_default = Path(__file__).resolve().parents[2]
    parser.add_argument(
        "--gantt",
        default=str(root_default / "project" / "gantt_chart.md"),
        help="Path to gantt_chart.md",
    )
    parser.add_argument(
        "--excel",
        default=str(root_default / "project" / "gantt_chart.xlsx"),
        help="Output path for .xlsx",
    )
    parser.add_argument(
        "--csv",
        default=str(root_default / "project" / "gantt_tasks.csv"),
        help="Output path for .csv",
    )
    args = parser.parse_known_args()[0]  # ignore unknown args (e.g. pytest flags)
    return Path(args.gantt), Path(args.excel), Path(args.csv)

GANTT_MD, EXCEL_OUT, CSV_OUT = _resolve_paths()

# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
DARK_BLUE   = "1F3864"
MID_BLUE    = "2E75B6"
LIGHT_BLUE  = "BDD7EE"
PALE_BLUE   = "DEEAF1"
AMBER       = "FFC000"
RED         = "FF0000"
GREEN       = "70AD47"
GREY        = "808080"
WHITE       = "FFFFFF"
LIGHT_GREY  = "F2F2F2"
MILESTONE_C = "7030A0"

# ---------------------------------------------------------------------------
# Parse the "Project management source table" from gantt_chart.md
# ---------------------------------------------------------------------------

def parse_source_table(md_path: Path) -> list[dict]:
    text = md_path.read_text(encoding="utf-8")

    # Find the section
    match = re.search(
        r"## Project management source table\s*\n(.*?)(?=\n## |\Z)",
        text, re.DOTALL
    )
    if not match:
        sys.exit("ERROR: Could not find '## Project management source table' in gantt_chart.md")

    section = match.group(1)
    lines = [l.strip() for l in section.strip().splitlines() if l.strip().startswith("|")]

    if len(lines) < 3:
        sys.exit("ERROR: Source table has fewer than 3 rows (need header + separator + data).")

    # Parse header
    header = [h.strip() for h in lines[0].strip("|").split("|")]
    rows = []
    for line in lines[2:]:          # skip separator row
        cells = [c.strip() for c in line.strip("|").split("|")]
        # pad or truncate to match header length
        while len(cells) < len(header):
            cells.append("")
        rows.append(dict(zip(header, cells)))

    return rows


def clean(val: str) -> str:
    return val.strip().strip("**").strip()


def get_owner(row: dict) -> str:
    """Return owner field, handling both 'Owner' (template v1) and legacy 'Owner / role'."""
    return clean(row.get("Owner") or row.get("Owner / role", ""))


def to_date(val: str) -> date | None:
    val = clean(val)
    try:
        return date.fromisoformat(val)
    except ValueError:
        return None


def to_int(val: str) -> int:
    try:
        return int(clean(val).replace("%", ""))
    except ValueError:
        return 0


# ---------------------------------------------------------------------------
# Helpers: styling
# ---------------------------------------------------------------------------

def header_style(ws, row: int, cols: int,
                 bg=DARK_BLUE, fg=WHITE, bold=True, size=11):
    fill = PatternFill("solid", fgColor=bg)
    font = Font(color=fg, bold=bold, size=size)
    align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for c in range(1, cols + 1):
        cell = ws.cell(row=row, column=c)
        cell.fill = fill
        cell.font = font
        cell.alignment = align


def thin_border():
    thin = Side(style="thin", color="CCCCCC")
    return Border(left=thin, right=thin, top=thin, bottom=thin)


def apply_borders(ws, min_row, max_row, min_col, max_col):
    bd = thin_border()
    for r in range(min_row, max_row + 1):
        for c in range(min_col, max_col + 1):
            ws.cell(row=r, column=c).border = bd


def set_col_widths(ws, widths: list[int]):
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w


def status_fill(status: str) -> PatternFill | None:
    s = status.lower()
    if "at risk" in s:
        return PatternFill("solid", fgColor="FFE699")
    if "not started" in s:
        return PatternFill("solid", fgColor=LIGHT_GREY)
    if "in progress" in s:
        return PatternFill("solid", fgColor="DDEBF7")
    if "complete" in s:
        return PatternFill("solid", fgColor="E2EFDA")
    return None


# ---------------------------------------------------------------------------
# Sheet 1 — Project View
# ---------------------------------------------------------------------------

def sheet_project_view(wb, rows: list[dict]):
    ws = wb.create_sheet("Project View")

    columns = [
        "Task ID", "Work Package", "Task", "Task Description",
        "Owner", "Time Requirements", "Resource Requirements",
        "Est. Start", "Est. End", "Duration (days)",
        "Milestone?", "Milestone Date", "Depends On",
        "Progress", "Status", "Notes"
    ]
    col_map = {
        "Task ID":               lambda r: clean(r.get("Task ID", "")),
        "Work Package":          lambda r: clean(r.get("Work package", "")),
        "Task":                  lambda r: clean(r.get("Task", "")),
        "Task Description":      lambda r: clean(r.get("Task description", "")),
        "Owner":                 lambda r: get_owner(r),
        "Time Requirements":     lambda r: clean(r.get("Time requirements", "—")),
        "Resource Requirements": lambda r: clean(r.get("Resource requirements", "")),
        "Est. Start":            lambda r: clean(r.get("Estimated start", "")),
        "Est. End":              lambda r: clean(r.get("Estimated end", "")),
        "Duration (days)":       lambda r: clean(r.get("Duration (business days)", "")),
        "Milestone?":            lambda r: clean(r.get("Milestone?", "")),
        "Milestone Date":        lambda r: clean(r.get("Milestone date", "")),
        "Depends On":            lambda r: clean(r.get("Depends on", "")),
        "Progress":              lambda r: clean(r.get("Progress", "")),
        "Status":                lambda r: clean(r.get("Status", "")),
        "Notes":                 lambda r: clean(r.get("Assumption / unknown notes", "")),
    }

    # Title
    ncols = len(columns)
    ws.merge_cells(f"A1:{get_column_letter(ncols)}1")
    title = ws["A1"]
    title.value = "Project View"
    title.font = Font(color=WHITE, bold=True, size=14)
    title.fill = PatternFill("solid", fgColor=DARK_BLUE)
    title.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 28

    header_style(ws, 2, ncols, bg=MID_BLUE)
    for c, col in enumerate(columns, 1):
        ws.cell(row=2, column=c).value = col
    ws.row_dimensions[2].height = 30

    for r_idx, row in enumerate(rows, 3):
        for c_idx, col in enumerate(columns, 1):
            val = col_map[col](row)
            cell = ws.cell(row=r_idx, column=c_idx)

            # Date columns
            if col in ("Est. Start", "Est. End", "Milestone Date"):
                d = to_date(val)
                cell.value = d if d else val
                if d:
                    cell.number_format = "YYYY-MM-DD"
            elif col == "Progress":
                pct = to_int(val)
                cell.value = pct / 100
                cell.number_format = "0%"
            elif col == "Duration (days)":
                try:
                    cell.value = int(val)
                except ValueError:
                    cell.value = val
            else:
                cell.value = val

            cell.alignment = Alignment(vertical="center", wrap_text=(c_idx >= 4))
            cell.border = thin_border()

            # Row shading
            bg = status_fill(row.get("Status", ""))
            if bg:
                cell.fill = bg
            elif r_idx % 2 == 0:
                cell.fill = PatternFill("solid", fgColor=PALE_BLUE)

            # Milestone rows — purple tint (overrides status colour)
            if clean(row.get("Milestone?", "")).lower() == "yes":
                cell.fill = PatternFill("solid", fgColor="EAD1DC")

        ws.row_dimensions[r_idx].height = 40

    set_col_widths(ws, [8, 22, 26, 42, 18, 22, 32, 14, 14, 10, 10, 14, 14, 10, 14, 40])
    ws.freeze_panes = "A3"
    ws.auto_filter.ref = f"A2:{get_column_letter(ncols)}2"


# ---------------------------------------------------------------------------
# Sheet 2 — Gantt Timeline
# ---------------------------------------------------------------------------

def sheet_gantt_timeline(wb, rows: list[dict]):
    ws = wb.create_sheet("Gantt Timeline")

    tasks = []
    for row in rows:
        start = to_date(clean(row.get("Estimated start", "")))
        end   = to_date(clean(row.get("Estimated end", "")))
        if start and end:
            tasks.append({
                "id":    clean(row.get("Task ID", "")),
                "task":  clean(row.get("Task", "")),
                "owner": get_owner(row),
                "start": start,
                "end":   end,
                "dur":   clean(row.get("Duration (business days)", "")),
                "ms":    clean(row.get("Milestone?", "")).lower() == "yes",
                "prog":  to_int(clean(row.get("Progress", "0"))),
                "status":clean(row.get("Status", "")),
            })

    if not tasks:
        ws["A1"] = "No tasks with valid start/end dates found."
        return

    proj_start = min(t["start"] for t in tasks)
    proj_end   = max(t["end"]   for t in tasks)

    # Generate week-start dates (Mondays)
    week_starts = []
    d = proj_start - timedelta(days=proj_start.weekday())  # prev Monday
    while d <= proj_end + timedelta(days=7):
        week_starts.append(d)
        d += timedelta(days=7)

    FIXED_COLS = 6   # ID | Task | Owner | Start | End | Duration
    DATA_COL_START = FIXED_COLS + 1

    # Title
    total_cols = FIXED_COLS + len(week_starts)
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=total_cols)
    tc = ws.cell(row=1, column=1, value="Gantt Timeline")
    tc.font  = Font(color=WHITE, bold=True, size=14)
    tc.fill  = PatternFill("solid", fgColor=DARK_BLUE)
    tc.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 28

    # Fixed headers
    fixed_headers = ["Task ID", "Task", "Owner", "Start", "End", "Duration (d)"]
    for c, h in enumerate(fixed_headers, 1):
        cell = ws.cell(row=2, column=c, value=h)
        cell.fill = PatternFill("solid", fgColor=MID_BLUE)
        cell.font = Font(color=WHITE, bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = thin_border()
    ws.row_dimensions[2].height = 22

    # Week headers
    today = date.today()
    for i, wk in enumerate(week_starts):
        c = DATA_COL_START + i
        cell = ws.cell(row=2, column=c)
        cell.value = wk
        cell.number_format = "MMM D"
        if wk <= today <= wk + timedelta(days=6):
            cell.fill = PatternFill("solid", fgColor=AMBER)
            cell.font = Font(color="000000", bold=True, size=8)
        else:
            cell.fill = PatternFill("solid", fgColor=MID_BLUE)
            cell.font = Font(color=WHITE, bold=True, size=8)
        cell.alignment = Alignment(horizontal="center", vertical="center", text_rotation=90)
        cell.border = thin_border()
        ws.column_dimensions[get_column_letter(c)].width = 5

    # Data rows
    for r_idx, task in enumerate(tasks, 3):
        ws.cell(row=r_idx, column=1, value=task["id"])
        ws.cell(row=r_idx, column=2, value=task["task"])
        ws.cell(row=r_idx, column=3, value=task["owner"])

        sc = ws.cell(row=r_idx, column=4, value=task["start"])
        sc.number_format = "YYYY-MM-DD"
        ec = ws.cell(row=r_idx, column=5, value=task["end"])
        ec.number_format = "YYYY-MM-DD"
        ws.cell(row=r_idx, column=6, value=task["dur"])

        for col_idx in range(1, FIXED_COLS + 1):
            cell = ws.cell(row=r_idx, column=col_idx)
            cell.alignment = Alignment(vertical="center")
            cell.border = thin_border()
            if r_idx % 2 == 0:
                cell.fill = PatternFill("solid", fgColor=PALE_BLUE)

        # Draw task bars
        bar_colour  = MILESTONE_C if task["ms"] else MID_BLUE
        bar_fill    = PatternFill("solid", fgColor=bar_colour)
        empty_fill  = PatternFill("solid", fgColor=LIGHT_GREY if r_idx % 2 == 0 else WHITE)

        for i, wk in enumerate(week_starts):
            c = DATA_COL_START + i
            cell = ws.cell(row=r_idx, column=c)
            cell.border = thin_border()
            wk_end = wk + timedelta(days=6)
            if task["start"] <= wk_end and task["end"] >= wk:
                cell.fill = bar_fill
                if task["ms"]:
                    cell.value = "◆"
                    cell.font  = Font(color=WHITE, size=7, bold=True)
                    cell.alignment = Alignment(horizontal="center", vertical="center")
            else:
                cell.fill = empty_fill

        ws.row_dimensions[r_idx].height = 18

    # Column widths for fixed columns
    for c, w in zip(range(1, FIXED_COLS + 1), [10, 28, 16, 13, 13, 8]):
        ws.column_dimensions[get_column_letter(c)].width = w

    ws.freeze_panes = f"{get_column_letter(DATA_COL_START)}3"


# ---------------------------------------------------------------------------
# Sheet 3 — Milestones
# ---------------------------------------------------------------------------

def sheet_milestones(wb, rows: list[dict]):
    ws = wb.create_sheet("Milestones")

    ms_rows = [r for r in rows if clean(r.get("Milestone?", "")).lower() == "yes"]

    ws.merge_cells("A1:G1")
    tc = ws["A1"]
    tc.value = "Milestones"
    tc.font  = Font(color=WHITE, bold=True, size=14)
    tc.fill  = PatternFill("solid", fgColor=DARK_BLUE)
    tc.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 28

    headers = ["Task ID", "Milestone / Task", "Milestone Date", "Owner", "Depends On", "Status", "Notes"]
    header_style(ws, 2, len(headers), bg=MILESTONE_C)
    for c, h in enumerate(headers, 1):
        ws.cell(row=2, column=c).value = h
    ws.row_dimensions[2].height = 22

    for r_idx, row in enumerate(ms_rows, 3):
        values = [
            clean(row.get("Task ID", "")),
            clean(row.get("Task", "")),
            to_date(clean(row.get("Milestone date", ""))) or clean(row.get("Milestone date", "")),
            get_owner(row),
            clean(row.get("Depends on", "")),
            clean(row.get("Status", "")),
            clean(row.get("Assumption / unknown notes", "")),
        ]
        for c, val in enumerate(values, 1):
            cell = ws.cell(row=r_idx, column=c, value=val)
            if c == 3 and isinstance(val, date):
                cell.number_format = "YYYY-MM-DD"
            cell.border = thin_border()
            cell.alignment = Alignment(vertical="center", wrap_text=(c >= 6))
            if r_idx % 2 == 0:
                cell.fill = PatternFill("solid", fgColor="F3E6F9")
        ws.row_dimensions[r_idx].height = 30

    apply_borders(ws, 2, 2 + len(ms_rows), 1, len(headers))
    set_col_widths(ws, [10, 32, 16, 18, 16, 14, 45])
    ws.freeze_panes = "A3"


# ---------------------------------------------------------------------------
# Sheet 4 — Resources
# ---------------------------------------------------------------------------

def sheet_resources(wb, rows: list[dict]):
    ws = wb.create_sheet("Resources")

    ws.merge_cells("A1:F1")
    tc = ws["A1"]
    tc.value = "Resource Requirements"
    tc.font  = Font(color=WHITE, bold=True, size=14)
    tc.fill  = PatternFill("solid", fgColor=DARK_BLUE)
    tc.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 28

    headers = ["Task ID", "Task", "Owner", "Time Requirements", "Resource Requirements", "Status", "Notes"]
    header_style(ws, 2, len(headers), bg="375623")
    for c, h in enumerate(headers, 1):
        ws.cell(row=2, column=c).value = h
    ws.row_dimensions[2].height = 22

    for r_idx, row in enumerate(rows, 3):
        values = [
            clean(row.get("Task ID", "")),
            clean(row.get("Task", "")),
            get_owner(row),
            clean(row.get("Time requirements", "—")),
            clean(row.get("Resource requirements", "")),
            clean(row.get("Status", "")),
            clean(row.get("Assumption / unknown notes", "")),
        ]
        for c, val in enumerate(values, 1):
            cell = ws.cell(row=r_idx, column=c, value=val)
            cell.border = thin_border()
            cell.alignment = Alignment(vertical="center", wrap_text=(c >= 4))
            if r_idx % 2 == 0:
                cell.fill = PatternFill("solid", fgColor="E2EFDA")

        sf = status_fill(values[5])   # Status is now index 5 (shifted by Time requirements)
        if sf:
            for c in range(1, len(headers) + 1):
                ws.cell(row=r_idx, column=c).fill = sf

        ws.row_dimensions[r_idx].height = 36

    set_col_widths(ws, [10, 28, 18, 28, 38, 14, 40])
    ws.freeze_panes = "A3"


# ---------------------------------------------------------------------------
# Sheet 5 — Assumptions & Unknowns
# ---------------------------------------------------------------------------

def sheet_assumptions(wb, rows: list[dict]):
    ws = wb.create_sheet("Assumptions Unknowns")

    ws.merge_cells("A1:D1")
    tc = ws["A1"]
    tc.value = "Assumptions and Unknowns"
    tc.font  = Font(color=WHITE, bold=True, size=14)
    tc.fill  = PatternFill("solid", fgColor=DARK_BLUE)
    tc.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 28

    headers = ["Task ID", "Task", "Type", "Assumption / Unknown"]
    header_style(ws, 2, len(headers), bg="843C0C")
    for c, h in enumerate(headers, 1):
        ws.cell(row=2, column=c).value = h
    ws.row_dimensions[2].height = 22

    r_idx = 3
    amber_fill  = PatternFill("solid", fgColor="FFF2CC")
    red_fill    = PatternFill("solid", fgColor="FFE0E0")
    normal_fill = PatternFill("solid", fgColor=LIGHT_GREY)

    for row in rows:
        note = clean(row.get("Assumption / unknown notes", ""))
        if not note or note.lower() in ("", "—", "-"):
            continue
        tl = clean(row.get("Timeline basis", ""))
        note_type = "Assumption" if "planning assumption" in note.lower() or "estimate" in note.lower() or "assumption" in tl.lower() else "Unknown / confirm"

        values = [
            clean(row.get("Task ID", "")),
            clean(row.get("Task", "")),
            note_type,
            note,
        ]
        for c, val in enumerate(values, 1):
            cell = ws.cell(row=r_idx, column=c, value=val)
            cell.border = thin_border()
            cell.alignment = Alignment(vertical="center", wrap_text=True)
            if "unknown" in note_type.lower():
                cell.fill = red_fill
            elif "assumption" in note_type.lower():
                cell.fill = amber_fill
            else:
                cell.fill = normal_fill
        ws.row_dimensions[r_idx].height = 40
        r_idx += 1

    set_col_widths(ws, [10, 28, 18, 60])
    ws.freeze_panes = "A3"


# ---------------------------------------------------------------------------
# CSV export
# ---------------------------------------------------------------------------

def export_csv(rows: list[dict], csv_path: Path):
    if not rows:
        return
    fieldnames = list(rows[0].keys())
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"  CSV  -> {csv_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not GANTT_MD.exists():
        sys.exit(f"ERROR: {GANTT_MD} not found. Create gantt_chart.md first.\n"
                 f"  Tip: pass --gantt <path> to target a different folder.")

    print(f"Reading {GANTT_MD} ...")
    rows = parse_source_table(GANTT_MD)
    print(f"  Found {len(rows)} rows in source table.")

    wb = openpyxl.Workbook()
    wb.remove(wb.active)   # remove default sheet

    print("Building sheets ...")
    sheet_project_view(wb, rows)
    sheet_gantt_timeline(wb, rows)
    sheet_milestones(wb, rows)
    sheet_resources(wb, rows)
    sheet_assumptions(wb, rows)

    wb.save(EXCEL_OUT)
    print(f"  XLSX -> {EXCEL_OUT}")

    export_csv(rows, CSV_OUT)
    print("Done.")


if __name__ == "__main__":
    main()
