# ARCHIVED — superseded by tools/scripts/create_project_intro_deck.py
# This was an early project-specific runtime-generated script.
# Kept for reference only; do not run.
"""
Runtime-generated script: creates project_intro_deck.pptx from
project_plan.md, gantt_tasks.csv, and company_style branding.
Generated by project-intro-slide-deck skill on 2026-05-07.
"""

from pathlib import Path
import csv
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT      = Path(__file__).parent.parent
PLAN_MD   = ROOT / "project_plan.md"
CSV_PATH  = ROOT / "gantt_tasks.csv"
OUT_PPTX  = ROOT / "project_intro_deck.pptx"

# ---------------------------------------------------------------------------
# Brand colours (from maclear_document_pdf.pdf)
# ---------------------------------------------------------------------------
BRAND_NAVY   = RGBColor(0x0F, 0x47, 0x61)   # #0F4761 primary heading/title
BRAND_TEAL   = RGBColor(0x17, 0x5E, 0x7A)   # #175E7A slightly lighter accent
LIGHT_GREY   = RGBColor(0xE3, 0xE3, 0xE3)   # #E3E3E3 backgrounds
MED_GREY     = RGBColor(0xA0, 0xA0, 0xA0)   # #A0A0A0 borders / secondary text
WHITE        = RGBColor(0xFF, 0xFF, 0xFF)
BLACK        = RGBColor(0x1A, 0x1A, 0x1A)
AMBER        = RGBColor(0xFF, 0xC0, 0x00)   # At risk highlight
RED_SOFT     = RGBColor(0xC0, 0x00, 0x00)   # Risk severity high
GREEN_SOFT   = RGBColor(0x70, 0xAD, 0x47)   # On track / complete

BODY_FONT    = "Aptos"
HEADING_FONT = "Aptos Display"

# Slide dimensions: widescreen 13.33" x 7.5"
SLIDE_W = Inches(13.33)
SLIDE_H = Inches(7.5)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def blank_slide(prs: Presentation) -> object:
    blank_layout = prs.slide_layouts[6]   # completely blank
    return prs.slides.add_slide(blank_layout)


def solid_fill(shape, color: RGBColor):
    shape.fill.solid()
    shape.fill.fore_color.rgb = color


def add_rect(slide, left, top, width, height, color: RGBColor, line=False):
    shape = slide.shapes.add_shape(1, left, top, width, height)   # MSO_SHAPE_TYPE.RECTANGLE = 1
    solid_fill(shape, color)
    if not line:
        shape.line.fill.background()
    else:
        shape.line.color.rgb = color
    return shape


def add_text_box(slide, text, left, top, width, height,
                 font_name=BODY_FONT, font_size=Pt(12),
                 bold=False, color=BLACK,
                 align=PP_ALIGN.LEFT, wrap=True, italic=False):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = wrap
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.name = font_name
    run.font.size = font_size
    run.font.bold = bold
    run.font.color.rgb = color
    run.font.italic = italic
    return txBox


def add_title_bar(slide, title_text, subtitle_text=""):
    """Dark navy bar across top ~1.5 inches."""
    bar = add_rect(slide, Inches(0), Inches(0), SLIDE_W, Inches(1.5), BRAND_NAVY)

    # Title text
    add_text_box(slide, title_text,
                 Inches(0.4), Inches(0.12), Inches(12.5), Inches(0.9),
                 font_name=HEADING_FONT, font_size=Pt(28), bold=True,
                 color=WHITE, align=PP_ALIGN.LEFT)

    # Subtitle / breadcrumb
    if subtitle_text:
        add_text_box(slide, subtitle_text,
                     Inches(0.4), Inches(1.0), Inches(12.5), Inches(0.38),
                     font_name=BODY_FONT, font_size=Pt(13), bold=False,
                     color=RGBColor(0xBD, 0xD7, 0xEE), align=PP_ALIGN.LEFT)

    # Thin accent line below bar
    add_rect(slide, Inches(0), Inches(1.5), SLIDE_W, Inches(0.04), BRAND_TEAL)


def add_footer(slide, text="Maclear | Website Update | Confidential"):
    add_rect(slide, Inches(0), Inches(7.3), SLIDE_W, Inches(0.2), BRAND_NAVY)
    add_text_box(slide, text,
                 Inches(0.3), Inches(7.3), Inches(12.7), Inches(0.2),
                 font_name=BODY_FONT, font_size=Pt(8), color=RGBColor(0xBD, 0xD7, 0xEE),
                 align=PP_ALIGN.LEFT)


def bullets(slide, items, left, top, width, height,
            font_size=Pt(13), color=BLACK, indent="  "):
    """Add a list of bullet strings to a text box."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    first = True
    for item in items:
        if first:
            p = tf.paragraphs[0]
            first = False
        else:
            p = tf.add_paragraph()
        p.space_before = Pt(3)
        run = p.add_run()
        run.text = f"  {item}" if not item.startswith(" ") else item
        run.font.name = BODY_FONT
        run.font.size = font_size
        run.font.color.rgb = color
    return txBox


def two_col_bullets(slide, left_title, left_items, right_title, right_items,
                    top=Inches(1.65), height=Inches(5.2)):
    col_w  = Inches(6.1)
    gap    = Inches(0.3)
    left_x = Inches(0.35)
    right_x = left_x + col_w + gap

    # Left column header
    add_rect(slide, left_x, top, col_w, Inches(0.38), BRAND_NAVY)
    add_text_box(slide, left_title, left_x + Inches(0.1), top, col_w, Inches(0.38),
                 font_name=HEADING_FONT, font_size=Pt(13), bold=True, color=WHITE)

    # Right column header
    add_rect(slide, right_x, top, col_w, Inches(0.38), MED_GREY)
    add_text_box(slide, right_title, right_x + Inches(0.1), top, col_w, Inches(0.38),
                 font_name=HEADING_FONT, font_size=Pt(13), bold=True, color=WHITE)

    # Left bullets
    bullets(slide, left_items,
            left_x, top + Inches(0.42), col_w, height - Inches(0.42),
            font_size=Pt(12))

    # Right bullets
    bullets(slide, right_items,
            right_x, top + Inches(0.42), col_w, height - Inches(0.42),
            font_size=Pt(12), color=RGBColor(0x60, 0x60, 0x60))


def simple_table(slide, headers, rows_data, left, top, width, row_height=Inches(0.42)):
    col_count = len(headers)
    col_w = width / col_count

    # Header row
    for c, h in enumerate(headers):
        x = left + c * col_w
        add_rect(slide, x, top, col_w, row_height, BRAND_NAVY)
        add_text_box(slide, h, x + Inches(0.05), top + Inches(0.05), col_w - Inches(0.1), row_height - Inches(0.05),
                     font_name=BODY_FONT, font_size=Pt(11), bold=True, color=WHITE)

    # Data rows
    for r_idx, row in enumerate(rows_data):
        y = top + (r_idx + 1) * row_height
        bg = LIGHT_GREY if r_idx % 2 == 0 else WHITE
        for c_idx, cell in enumerate(row):
            x = left + c_idx * col_w
            add_rect(slide, x, y, col_w, row_height, bg)
            cell_color = BLACK
            if "At risk" in str(cell):
                cell_color = RGBColor(0xC0, 0x00, 0x00)
                bg_fill = RGBColor(0xFF, 0xE6, 0x99)
                add_rect(slide, x, y, col_w, row_height, bg_fill)
            elif "TBD" in str(cell) or "Not provided" in str(cell):
                cell_color = RGBColor(0x70, 0x50, 0x00)
            add_text_box(slide, str(cell),
                         x + Inches(0.05), y + Inches(0.04),
                         col_w - Inches(0.1), row_height - Inches(0.05),
                         font_name=BODY_FONT, font_size=Pt(10), color=cell_color)


# ---------------------------------------------------------------------------
# Load task data
# ---------------------------------------------------------------------------

def load_tasks():
    if not CSV_PATH.exists():
        return []
    with CSV_PATH.open(encoding="utf-8") as f:
        return list(csv.DictReader(f))


def clean(val):
    if val is None:
        return ""
    return str(val).strip().replace("—", "--").replace("→", "->").replace("–", "-").replace("�", "-").replace("◆", "*")


# ---------------------------------------------------------------------------
# Slides
# ---------------------------------------------------------------------------

def slide_title(prs):
    slide = blank_slide(prs)

    # Full navy background
    add_rect(slide, Inches(0), Inches(0), SLIDE_W, SLIDE_H, BRAND_NAVY)

    # Light grey bottom band
    add_rect(slide, Inches(0), Inches(5.5), SLIDE_W, Inches(2.0), LIGHT_GREY)

    # Accent teal bar
    add_rect(slide, Inches(0), Inches(5.4), SLIDE_W, Inches(0.12), BRAND_TEAL)

    # Main title
    add_text_box(slide, "Website Update",
                 Inches(0.6), Inches(1.2), Inches(11), Inches(1.4),
                 font_name=HEADING_FONT, font_size=Pt(48), bold=True, color=WHITE)

    # Subtitle
    add_text_box(slide, "Project Introduction",
                 Inches(0.6), Inches(2.7), Inches(11), Inches(0.7),
                 font_name=HEADING_FONT, font_size=Pt(28), bold=False,
                 color=RGBColor(0xBD, 0xD7, 0xEE))

    # Divider
    add_rect(slide, Inches(0.6), Inches(3.5), Inches(2.5), Inches(0.06), BRAND_TEAL)

    # Meta info in grey band
    add_text_box(slide, "Yujia Yao, Data Scientist   |   Maclear   |   May 2026",
                 Inches(0.6), Inches(5.6), Inches(10), Inches(0.5),
                 font_name=BODY_FONT, font_size=Pt(14), color=BRAND_NAVY)

    add_text_box(slide, "Confidential — Internal Use",
                 Inches(0.6), Inches(6.2), Inches(10), Inches(0.4),
                 font_name=BODY_FONT, font_size=Pt(11), italic=True,
                 color=MED_GREY)


def slide_why(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Why This Project Matters", "Business problem and strategic value")
    add_footer(slide)

    items = [
        "bullet  Current website contains outdated and inaccurate content with no reliable update process",
        "bullet  Manual updates risk inconsistency, formatting damage, and unauthorized content changes",
        "bullet  A reusable update pipeline will improve SEO, increase customer engagement, and reduce operational risk",
        "bullet  Prevents outdated or unsupported content from remaining on the live site",
        "bullet  Supports Maclear's commitment to precision, transparency, and controlled delivery",
    ]
    display = [i.replace("bullet  ", "•  ") for i in items]
    bullets(slide, display,
            Inches(0.5), Inches(1.7), Inches(12.3), Inches(5.3),
            font_size=Pt(15), color=BLACK)


def slide_scope(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Scope and Deliverables", "What is — and is not — included")
    add_footer(slide)

    in_scope = [
        "•  Review current website content — identify outdated sections",
        "•  Confirm approved replacement content with client",
        "•  Build reusable content-update pipeline",
        "•  Test pipeline in staging environment before any live change",
        "•  Apply approved updates to live website",
        "•  Document pipeline for future update cycles",
    ]
    out_scope = [
        "•  Creating original content (LLM cannot generate beyond approved source)",
        "•  New website functionality or features",
        "•  Website redesign or restyling",
        "•  Modifying content that is already approved",
        "•  Unrelated technical changes to the website platform",
    ]
    two_col_bullets(slide, "IN SCOPE", in_scope, "OUT OF SCOPE", out_scope)


def slide_success(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "What Success Looks Like", "Acceptance criteria")
    add_footer(slide)

    items = [
        "✔  Pipeline updates content accurately — zero hallucinated or unsupported output",
        "✔  Approved existing content is fully preserved after every update",
        "✔  Formatting and page structure are intact post-update",
        "✔  No update reaches the live site without explicit written approval",
        "✔  Pipeline is reusable and documented for future update cycles",
    ]
    bullets(slide, items,
            Inches(0.5), Inches(1.7), Inches(12.3), Inches(5.3),
            font_size=Pt(16), color=BLACK)

    # Key constraint box
    add_rect(slide, Inches(0.5), Inches(6.1), Inches(12.3), Inches(0.55), RGBColor(0xFF, 0xE6, 0x99))
    add_text_box(slide,
                 "Mandatory constraint: LLM must not generate new content beyond the approved source material",
                 Inches(0.6), Inches(6.1), Inches(12.1), Inches(0.55),
                 font_name=BODY_FONT, font_size=Pt(12), bold=True,
                 color=RGBColor(0x7F, 0x50, 0x00))


def slide_timeline(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Project Timeline", "Apr 1 – Jun 1, 2026   |   Estimated schedule")
    add_footer(slide)

    phases = [
        ("Phase 1: Initiation",              "Apr 1–7",      0.0,   0.14,  BRAND_NAVY),
        ("Phase 2: Content Audit",           "Apr 2–6",      0.0,   0.09,  BRAND_TEAL),
        ("Phase 3: Pipeline Development",    "Apr 8–24",     0.14,  0.40,  RGBColor(0x1F, 0x68, 0x90)),
        ("Phase 4: Testing & QA",            "Apr 27–May 1", 0.54,  0.14,  RGBColor(0x2E, 0x75, 0xB6)),
        ("Phase 5: Review & Approval",       "May 4–8",      0.68,  0.12,  RGBColor(0x26, 0x8B, 0x8B)),
        ("Phase 6: Deployment",              "May 11–14",    0.80,  0.11,  RGBColor(0x70, 0xAD, 0x47)),
        ("Phase 7: Docs & Closeout",         "Apr 27–May 15",0.54,  0.32,  RGBColor(0x40, 0x80, 0x80)),
    ]

    chart_left  = Inches(0.5)
    chart_top   = Inches(1.7)
    chart_w     = Inches(12.3)
    row_h       = Inches(0.56)
    bar_h       = Inches(0.38)
    bar_top_off = Inches(0.09)

    for i, (label, dates, start_frac, dur_frac, color) in enumerate(phases):
        y = chart_top + i * row_h

        # Background row
        bg_col = LIGHT_GREY if i % 2 == 0 else WHITE
        add_rect(slide, chart_left, y, chart_w, row_h, bg_col)

        # Phase bar
        bar_x = chart_left + chart_w * start_frac
        bar_w = max(chart_w * dur_frac, Inches(0.15))
        add_rect(slide, bar_x, y + bar_top_off, bar_w, bar_h, color)

        # Label on bar
        add_text_box(slide, label,
                     bar_x + Inches(0.08), y + bar_top_off + Inches(0.04),
                     bar_w - Inches(0.1), bar_h - Inches(0.08),
                     font_name=BODY_FONT, font_size=Pt(9), bold=True, color=WHITE)

        # Date label to right
        add_text_box(slide, dates,
                     bar_x + bar_w + Inches(0.08), y + bar_top_off + Inches(0.06),
                     Inches(2.0), bar_h,
                     font_name=BODY_FONT, font_size=Pt(9), color=MED_GREY)

    # Today marker
    today_frac  = 0.71   # May 7 in the Apr-Jun range
    today_x     = chart_left + chart_w * today_frac
    add_rect(slide, today_x, chart_top - Inches(0.05),
             Inches(0.04), row_h * len(phases) + Inches(0.05),
             AMBER)
    add_text_box(slide, "TODAY\nMay 7",
                 today_x - Inches(0.25), chart_top - Inches(0.45), Inches(0.7), Inches(0.4),
                 font_name=BODY_FONT, font_size=Pt(8), bold=True,
                 color=RGBColor(0x7F, 0x50, 0x00), align=PP_ALIGN.CENTER)

    # Key dates note
    add_text_box(slide,
                 "Start: Apr 1, 2026   |   Prototype target: Apr 24   |   Approval gate: May 8   |   Live update: May 12   |   Close: May 15 (Hard deadline: Jun 1)",
                 Inches(0.5), Inches(6.85), Inches(12.3), Inches(0.35),
                 font_name=BODY_FONT, font_size=Pt(9), italic=True, color=MED_GREY,
                 align=PP_ALIGN.CENTER)


def slide_milestones(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Key Milestones", "Four critical checkpoints")
    add_footer(slide)

    headers = ["Milestone", "Target Date", "Owner", "Status"]
    rows_data = [
        ["Prototype (pipeline v1) released",    "Apr 24, 2026",  "Yujia Yao",     "At risk — confirm"],
        ["Approval to deploy",                  "May 8, 2026",   "Jesus Calderon","Not started"],
        ["Live website updated",                "May 12, 2026",  "Yujia Yao",     "Not started"],
        ["Project complete (hard deadline)",    "Jun 1, 2026",   "Jesus Calderon","Not started"],
    ]

    simple_table(slide, headers, rows_data,
                 left=Inches(0.5), top=Inches(1.75),
                 width=Inches(12.3), row_height=Inches(0.85))

    add_text_box(slide,
                 "M1 is flagged At risk: the Apr 24 target has passed as of today (May 7). Confirm actual pipeline status before re-baselining.",
                 Inches(0.5), Inches(6.15), Inches(12.3), Inches(0.5),
                 font_name=BODY_FONT, font_size=Pt(10), italic=True,
                 color=RGBColor(0xC0, 0x00, 0x00))


def slide_workstreams(prs, tasks):
    slide = blank_slide(prs)
    add_title_bar(slide, "Workstreams and Task Summary", "7 phases | 16 tasks | single executor")
    add_footer(slide)

    headers = ["Phase", "Key Tasks", "Est. Duration", "Status"]
    rows_data = [
        ["1. Initiation",           "Kickoff, access setup, API permissions, content collection",       "~1 week",  "Confirm status"],
        ["2. Content Audit",        "Review current website; identify outdated sections",               "3 days",   "Confirm status"],
        ["3. Pipeline Dev",         "Architecture design, pipeline build, staging environment setup",   "~3 weeks", "Confirm status"],
        ["4. Testing & QA",         "Staging tests: accuracy, formatting, approval workflow",           "1 week",   "Confirm status"],
        ["5. Review & Approval",    "Owner review of proposed changes + written approval gate",         "1 week",   "Not started"],
        ["6. Deployment",           "Live update + post-deployment verification",                       "4 days",   "Not started"],
        ["7. Docs & Closeout",      "Pipeline documentation + final sign-off",                          "3 days",   "Not started"],
    ]

    simple_table(slide, headers, rows_data,
                 left=Inches(0.35), top=Inches(1.65),
                 width=Inches(12.6), row_height=Inches(0.68))

    add_text_box(slide,
                 "Total tasks: 16  +  4 milestones   |   Single resource: Yujia Yao (full-time Mon–Fri)",
                 Inches(0.35), Inches(6.85), Inches(12.6), Inches(0.35),
                 font_name=BODY_FONT, font_size=Pt(10), bold=True, color=BRAND_NAVY)


def slide_roles(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Roles and Responsibilities", "Who does what")
    add_footer(slide)

    headers = ["Role", "Person / Team", "Responsibilities", "Availability"]
    rows_data = [
        ["Project Lead / Developer",   "Yujia Yao",              "All execution: audit, build, test, deploy, document",   "Full-time Mon–Fri"],
        ["Decision-Maker / Approver",  "Jesus Calderon",         "Scope, budget, schedule; two hard approval gates",      "TBD — confirm"],
        ["Content Provider",           "Maclear / Alco Insights","Deliver approved source content; confirm content package","External — TBD"],
        ["AI/API Services",            "OpenAI / Claude",        "LLM component of the content-update pipeline",          "Subject to license"],
        ["Final Approver",             "TBD — Not provided",     "Approve final deliverables",                             "TBD — confirm"],
    ]

    simple_table(slide, headers, rows_data,
                 left=Inches(0.35), top=Inches(1.65),
                 width=Inches(12.6), row_height=Inches(0.78))

    add_text_box(slide,
                 "Risk: Yujia Yao is the sole executor. Any absence halts all project work. No current mitigation.",
                 Inches(0.35), Inches(6.85), Inches(12.6), Inches(0.35),
                 font_name=BODY_FONT, font_size=Pt(10), bold=True,
                 color=RGBColor(0xC0, 0x00, 0x00))


def slide_risks(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Key Risks and Mitigations", "Top 5 risks — all rated High severity")
    add_footer(slide)

    headers = ["Risk", "Prob.", "Impact", "Mitigation"]
    rows_data = [
        ["Client content not delivered on time",            "High",   "High", "Confirm delivery date now; escalate if delayed"],
        ["LLM generates unsupported content",               "Medium", "High", "LLM reformats only — never generates new content"],
        ["Approved content overwritten by pipeline bug",    "Medium", "High", "Pre/post diff review + approval gate before live deploy"],
        ["Approval gate delayed (Jesus Calderon)",          "Medium", "High", "Set 2-day response expectation; escalate early"],
        ["Single-resource risk — Yujia Yao only executor",  "Medium", "High", "Flag to Jesus Calderon — no current mitigation"],
    ]

    simple_table(slide, headers, rows_data,
                 left=Inches(0.35), top=Inches(1.65),
                 width=Inches(12.6), row_height=Inches(0.8))


def slide_open_decisions(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Open Decisions and Confirmations Needed", "Items blocking schedule re-baseline")
    add_footer(slide)

    items_high = [
        "⚠  Actual task status as of today (May 7) — has the prototype been delivered?",
        "⚠  Who is the final deliverable approver? (left blank in questionnaire)",
        "⚠  Has approved source content been received from Maclear / Alco Insights?",
        "⚠  Are website admin access and AI/API access confirmed?",
    ]
    items_med = [
        "●  Should automatic update functionality be in scope?",
        "●  Should style/design updates be included?",
        "●  How much automation vs. manual approval should the pipeline require?",
        "●  Confirmed budget ceiling (range given: $50–$5,000)",
    ]

    # High priority label
    add_rect(slide, Inches(0.35), Inches(1.65), Inches(12.6), Inches(0.35), RED_SOFT)
    add_text_box(slide, "HIGH PRIORITY — must answer this week",
                 Inches(0.45), Inches(1.65), Inches(12.4), Inches(0.35),
                 font_name=BODY_FONT, font_size=Pt(11), bold=True, color=WHITE)

    bullets(slide, items_high,
            Inches(0.5), Inches(2.05), Inches(12.3), Inches(2.2),
            font_size=Pt(13), color=RED_SOFT)

    # Medium priority label
    add_rect(slide, Inches(0.35), Inches(4.35), Inches(12.6), Inches(0.35), MED_GREY)
    add_text_box(slide, "MEDIUM PRIORITY — needed before pipeline build is finalized",
                 Inches(0.45), Inches(4.35), Inches(12.4), Inches(0.35),
                 font_name=BODY_FONT, font_size=Pt(11), bold=True, color=WHITE)

    bullets(slide, items_med,
            Inches(0.5), Inches(4.75), Inches(12.3), Inches(2.0),
            font_size=Pt(13), color=RGBColor(0x40, 0x40, 0x40))


def slide_next_steps(prs):
    slide = blank_slide(prs)
    add_title_bar(slide, "Recommended Next Steps", "Actions for the week of May 7, 2026")
    add_footer(slide)

    steps = [
        ("1", "Confirm current task status with Yujia Yao — update progress on all early tasks immediately",    "This week"),
        ("2", "Confirm final deliverable approver with Jesus Calderon",                                          "This week"),
        ("3", "Confirm approved source content received from Maclear / Alco Insights",                           "This week"),
        ("4", "Confirm website access and AI/API access are secured",                                            "This week"),
        ("5", "Answer three open scope decisions: automation, design updates, approval flow",                    "This week"),
        ("6", "Re-baseline the project schedule after confirming actual task status",                            "After steps 1–5"),
        ("7", "Proceed to Gantt chart execution tracking with updated progress",                                  "After step 6"),
    ]

    top = Inches(1.72)
    row_h = Inches(0.72)
    for i, (num, action, timing) in enumerate(steps):
        y = top + i * row_h
        bg = LIGHT_GREY if i % 2 == 0 else WHITE
        add_rect(slide, Inches(0.35), y, Inches(12.6), row_h, bg)

        # Number circle
        add_rect(slide, Inches(0.4), y + Inches(0.12), Inches(0.44), Inches(0.44), BRAND_NAVY)
        add_text_box(slide, num,
                     Inches(0.4), y + Inches(0.12), Inches(0.44), Inches(0.44),
                     font_name=HEADING_FONT, font_size=Pt(14), bold=True,
                     color=WHITE, align=PP_ALIGN.CENTER)

        # Action text
        add_text_box(slide, action,
                     Inches(0.95), y + Inches(0.1), Inches(10.5), Inches(0.52),
                     font_name=BODY_FONT, font_size=Pt(12), color=BLACK)

        # Timing tag
        add_rect(slide, Inches(11.55), y + Inches(0.16), Inches(1.2), Inches(0.36),
                 BRAND_TEAL if "week" in timing.lower() else LIGHT_GREY)
        add_text_box(slide, timing,
                     Inches(11.55), y + Inches(0.16), Inches(1.2), Inches(0.36),
                     font_name=BODY_FONT, font_size=Pt(9), bold=True,
                     color=WHITE if "week" in timing.lower() else MED_GREY,
                     align=PP_ALIGN.CENTER)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print(f"Building project_intro_deck.pptx ...")

    prs = Presentation()
    prs.slide_width  = SLIDE_W
    prs.slide_height = SLIDE_H

    tasks = load_tasks()
    print(f"  Loaded {len(tasks)} tasks from gantt_tasks.csv")

    slide_title(prs)
    print("  Slide 1: Title")

    slide_why(prs)
    print("  Slide 2: Why This Project Matters")

    slide_scope(prs)
    print("  Slide 3: Scope and Deliverables")

    slide_success(prs)
    print("  Slide 4: Success Criteria")

    slide_timeline(prs)
    print("  Slide 5: Timeline Overview")

    slide_milestones(prs)
    print("  Slide 6: Key Milestones")

    slide_workstreams(prs, tasks)
    print("  Slide 7: Workstreams and Task Summary")

    slide_roles(prs)
    print("  Slide 8: Roles and Responsibilities")

    slide_risks(prs)
    print("  Slide 9: Risks and Mitigations")

    slide_open_decisions(prs)
    print("  Slide 10: Open Decisions")

    slide_next_steps(prs)
    print("  Slide 11: Next Steps")

    prs.save(OUT_PPTX)
    print(f"  Saved -> {OUT_PPTX}")
    print("Done.")


if __name__ == "__main__":
    main()
